### ISSUE TITLE
Allow to customize log path

### ISSUE THREAD

**Issue by jvanbruegge** [Treeniks/isabelle-lsp.nvim#3]
Currently this is hard-coded to the `Documents` directory

**Comment by Treeniks** [comment]
Ah, seems like I accidentally enabled logging in 243c1a7617f171867ccff925e5f871ebad2207f9. I wanted to keep that commented out and only use it locally, my bad. I added explicit options to enable and customize logging with commit 5c4f61e140d1b4d728d67b99832bc63b2b94ae92.

**Comment by jvanbruegge** [comment]
Thanks!
