### ISSUE TITLE
LSP server crashing

### ISSUE THREAD

**Issue by CadeMichael** [Treeniks/isabelle-lsp.nvim#7]
When entering a .thy file I get the following error message indicating that the isabelle-lsp isn't working. I'm not sure if this is a versioning issue I am using isabelle2024.

```
LSP[isabelle] Unknown option "vscode_html_output"
The error(s) above occurred in command-line option "-o"
```

**Comment by Treeniks** [comment]
Please have a thorough look at the [README](https://github.com/Treeniks/isabelle-lsp.nvim?tab=readme-ov-file#isabelle). This plugin requires additions to Isabelle that are not present in Isabelle2024.
